name: build docs (PR)

on:
  pull_request:
    branches: ['main']
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install --upgrade pip
      - run: |
          pip install -r requirements.txt
      - run: rm -rf site
      - run: "sed -i -e 's|^#\\?site_url:.*|site_url: https://docs-kb.tds.cscs.ch/${{ github.event.pull_request.number }}|' mkdocs.yml"
      - run: cat mkdocs.yml
      - run: mkdocs build
      - run: |
          mkdir upload
          env --chdir=site tar -czf ../upload/site.tar.gz .
          echo ${{ github.event.pull_request.number }} > upload/pr_number.txt
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: upload
          if-no-files-found: error
