name: Upload docs

on:
  workflow_run:
    workflows: ["build docs (PR)"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ github.ref_name }}"
          echo "${{ github }}"
          ls -alh
      - run: |
          if [[ -n "${{ secrets.UPLOAD_TOKEN }}" ]] ; then
            echo "secrets.UPLOAD_TOKEN is non-empty"
          else
            echo "secrets.UPLOAD_TOKEN is empty"
          fi
      - env:
          MY_SECRET: ${{ secrets.UPLOAD_TOKEN }}
        run: |
          if [[ -n "$MY_SECRET" ]] ; then
            echo "MY_SECRET is non-empty"
          else
            echo "MY_SECRET is empty"
          fi
